CREATE TABLE User (
       ID STRING(128) NOT NULL,
       Name STRING(128) NOT NULL,
       Age INT64 NOT NULL,
) PRIMARY KEY(ID);

CREATE TABLE Item (
       ID STRING(128) NOT NULL,
       Name STRING(128) NOT NULL,
) PRIMARY KEY(ID);
